-- Seed data: your existing collection (103 titles).
-- Run AFTER schema.sql. Safe to skip if you would rather start empty.

insert into public.listings (type, title, artist, year, used_price, good_price) values
  ('VHS', '101 Dalmatians', 'Walt Disney', '1961', 1, 3),
  ('VHS', 'Aladdin', 'Walt Disney', '1992', 1, 3),
  ('VHS', 'Alice in Wonderland', 'Walt Disney', '1951', 1, 3),
  ('VHS', 'An American Tail', 'Universal / Amblin', '1986', 1, 3),
  ('VHS', 'Anastasia', '20th Century Fox', '1997', 1, 3),
  ('VHS', 'Air Bud', 'Walt Disney', '1997', 1, 3),
  ('VHS', 'Air Bud (Disney Presents)', 'Walt Disney', '1997', 1, 3),
  ('VHS', 'Air Bud: World Pup', 'Walt Disney', '2000', 1, 3),
  ('VHS', 'Babe', 'Universal', '1995', 1, 3),
  ('VHS', 'Beauty and the Beast', 'Walt Disney', '1991', 1, 3),
  ('VHS', 'Blade Runner: The Director'''s Cut', 'Warner Bros.', '1992', 1, 3),
  ('VHS', 'Blue'''s Clues: Telling Time with Blue', 'Nickelodeon / Paramount', '2002', 1, 3),
  ('VHS', 'The Brave Little Toaster', 'Hyperion / Disney', '1987', 1, 3),
  ('VHS', 'The Brave Little Toaster (2nd copy)', 'Hyperion / Disney', '1987', 1, 3),
  ('VHS', 'Bring It On', 'Universal', '2000', 1, 3),
  ('VHS', 'Buck (horse film)', 'MCA / Universal', '1995', 1, 3),
  ('VHS', 'Casper', 'Universal', '1995', 1, 3),
  ('VHS', 'Charlotte'''s Web', 'Paramount', '1973', 1, 3),
  ('VHS', 'Cinderella', 'Walt Disney', '1950', 1, 3),
  ('VHS', 'Cinderella II: Dreams Come True', 'Walt Disney', '2002', 1, 3),
  ('VHS', 'Clifford the Big Red Dog: Clifford Tries His Best!', 'Scholastic', '2001', 1, 3),
  ('VHS', 'D2: The Mighty Ducks', 'Walt Disney', '1994', 1, 3),
  ('VHS', 'D3: The Mighty Ducks', 'Walt Disney', '1996', 1, 3),
  ('VHS', 'Dumbo', 'Walt Disney', '1941', 1, 3),
  ('VHS', 'The Easter Story Keepers', '20th Century Fox', '1998', 1, 3),
  ('VHS', 'Fantasia', 'Walt Disney', '1940', 1, 3),
  ('VHS', 'The Fox and the Hound', 'Walt Disney', '1981', 1, 3),
  ('VHS', 'Free Willy', 'Warner Bros.', '1993', 1, 3),
  ('VHS', 'A Goofy Movie', 'Walt Disney', '1995', 1, 3),
  ('VHS', 'The Great Mouse Detective', 'Walt Disney', '1986', 1, 3),
  ('VHS', 'Homeward Bound: The Incredible Journey', 'Walt Disney', '1993', 1, 3),
  ('VHS', 'Homeward Bound II: Lost in San Francisco', 'Walt Disney', '1996', 1, 3),
  ('VHS', 'Hook', 'TriStar / Columbia', '1991', 1, 3),
  ('VHS', 'It Takes Two', 'Warner Bros.', '1995', 1, 3),
  ('VHS', 'James and the Giant Peach', 'Walt Disney', '1996', 1, 3),
  ('VHS', 'Jingle All the Way', '20th Century Fox', '1996', 1, 3),
  ('VHS', 'The Jungle Book', 'Walt Disney', '1967', 1, 3),
  ('VHS', 'A Kid in King Arthur'''s Court', 'Walt Disney', '1995', 1, 3),
  ('VHS', 'Lady and the Tramp', 'Walt Disney', '1955', 1, 3),
  ('VHS', 'The Lion King', 'Walt Disney', '1994', 1, 3),
  ('VHS', 'The Little Mermaid', 'Walt Disney', '1989', 1, 3),
  ('VHS', 'Madeline and the Easter Bonnet', 'Sony Wonder', '1996', 1, 3),
  ('VHS', 'Mary Poppins', 'Walt Disney', '1964', 1, 3),
  ('VHS', 'Mickey'''s Magical Christmas: Snowed In at the House of Mouse', 'Walt Disney', '2001', 1, 3),
  ('VHS', 'The Mighty Ducks', 'Walt Disney', '1992', 1, 3),
  ('VHS', 'Monsters, Inc.', 'Disney / Pixar', '2001', 1, 3),
  ('VHS', 'Muppet Treasure Island', 'Walt Disney / Jim Henson', '1996', 1, 3),
  ('VHS', 'Muppet Treasure Island (2nd copy)', 'Walt Disney / Jim Henson', '1996', 1, 3),
  ('VHS', 'Now and Then', 'New Line', '1995', 1, 3),
  ('VHS', 'Once Upon a Forest', '20th Century Fox', '1993', 1, 3),
  ('VHS', 'The Parent Trap', 'Walt Disney', '1998', 1, 3),
  ('VHS', 'Peter Pan (Special Edition)', 'Walt Disney', '1953', 1, 3),
  ('VHS', 'Pinocchio', 'Walt Disney', '1940', 1, 3),
  ('VHS', 'Pocahontas (Masterpiece)', 'Walt Disney', '1995', 1, 3),
  ('VHS', 'Pocahontas (Gold Collection)', 'Walt Disney', '1995', 1, 3),
  ('VHS', 'Pooh'''s Grand Adventure: The Search for Christopher Robin', 'Walt Disney', '1997', 1, 3),
  ('VHS', 'Pooh'''s Grand Adventure (2nd copy)', 'Walt Disney', '1997', 1, 3),
  ('VHS', 'The Rescuers Down Under', 'Walt Disney', '1990', 1, 3),
  ('VHS', 'Richie Rich', 'Warner Bros.', '1994', 1, 3),
  ('VHS', 'Rookie of the Year', '20th Century Fox', '1993', 1, 3),
  ('VHS', 'The Sandlot', '20th Century Fox', '1993', 1, 3),
  ('VHS', 'Sleeping Beauty', 'Walt Disney', '1959', 1, 3),
  ('VHS', 'Snow White and the Seven Dwarfs', 'Walt Disney', '1937', 1, 3),
  ('VHS', 'Tales of Beatrix Potter', 'Family Home Entertainment', '1995', 1, 3),
  ('VHS', 'Tarzan', 'Walt Disney', '1999', 1, 3),
  ('VHS', 'Teenage Mutant Ninja Turtles: The Great Boldini', 'Family Home Entertainment', '1990', 1, 3),
  ('VHS', 'Teenage Mutant Ninja Turtles II: The Secret of the Ooze', 'New Line', '1991', 1, 3),
  ('VHS', 'Tom and Huck', 'Walt Disney', '1995', 1, 3),
  ('VHS', 'Toy Story', 'Disney / Pixar', '1995', 1, 3),
  ('VHS', 'Toy Story 2', 'Disney / Pixar', '1999', 1, 3),
  ('VHS', 'Wild America', 'Warner Bros.', '1997', 1, 3),
  ('VHS', 'Winnie the Pooh: ...And Christmas Too', 'Walt Disney', '1991', 1, 3),
  ('VHS', 'Winnie the Pooh: Newfound Friends', 'Walt Disney', '1998', 1, 3),
  ('DVD', 'All-Star Alphabet (Sesame Street)', 'Sony Wonder', '2005', 2, 4),
  ('DVD', 'The Best of Elmo (Sesame Street)', 'Sony Wonder', '1994', 2, 4),
  ('DVD', 'Cars', 'Disney / Pixar', '2006', 4, 8),
  ('DVD', 'Dora Celebrates Three Kings Day!', 'Nickelodeon', '2005', 2, 4),
  ('DVD', 'Elf', 'New Line', '2003', 3, 6),
  ('DVD', 'Elmo Visits the Firehouse (Sesame Street)', 'Sony Wonder', '2002', 2, 4),
  ('DVD', 'Elmo'''s World (Sesame Street)', 'Sony Wonder', '2000', 2, 4),
  ('DVD', 'Elmo'''s World: Pets! (Sesame Street)', 'Sony Wonder', '2006', 2, 4),
  ('DVD', 'Frozen', 'Walt Disney', '2013', 4, 7),
  ('DVD', 'The Great Numbers Game (Sesame Street)', 'Sesame Workshop', '2009', 2, 4),
  ('DVD', 'Home Alone', '20th Century Fox', '1990', 3, 6),
  ('DVD', 'Home Alone 2: Lost in New York', '20th Century Fox', '1992', 3, 6),
  ('DVD', 'The Incredibles', 'Disney / Pixar', '2004', 4, 8),
  ('DVD', 'Learning About Numbers Double Feature (Sesame Street)', 'Sesame Workshop', '2007', 2, 4),
  ('DVD', 'Learning About Numbers Double Feature (2nd copy)', 'Sesame Workshop', '2007', 2, 4),
  ('DVD', 'The Lord of the Rings (Widescreen)', 'New Line', '2001', 3, 6),
  ('DVD', 'The Many Adventures of Winnie the Pooh (Friendship Edition)', 'Walt Disney', '1977', 3, 6),
  ('DVD', 'Minnie'''s Masquerade (Mickey Mouse Clubhouse)', 'Walt Disney', '2011', 2, 4),
  ('DVD', 'Mrs. Doubtfire (Behind-the-Seams Edition)', '20th Century Fox', '1993', 3, 6),
  ('DVD', 'Pooh'''s Grand Adventure: The Search for Christopher Robin', 'Walt Disney', '1997', 3, 6),
  ('DVD', 'Ready for School! (Sesame Street)', 'Sesame Workshop', '2009', 2, 4),
  ('DVD', 'Toy Story 3', 'Disney / Pixar', '2010', 4, 8),
  ('CD', 'Stunt', 'Barenaked Ladies', '1998', 2, 4),
  ('CD', 'Breakaway', 'Kelly Clarkson', '2004', 2, 4),
  ('CD', 'A New Day Has Come', 'Celine Dion', '2002', 2, 4),
  ('CD', 'Home', 'Dixie Chicks', '2002', 2, 4),
  ('CD', 'Faith', 'Faith Hill', '1998', 2, 4),
  ('CD', 'Now That'''s What I Call Music! 42', 'Various Artists', '2012', 2, 4),
  ('CD', 'Savage Garden', 'Savage Garden', '1997', 2, 4),
  ('CD', '...Baby One More Time', 'Britney Spears', '1999', 2, 4);
